--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PELIGROSOS
--------------------------------------------------------

  CREATE TABLE "HR"."PELIGROSOS" 
   (	"PELIGROSOS_ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDOS" VARCHAR2(40 BYTE), 
	"DNI" NUMBER, 
	"FECHA_NACIMIENTO" DATE, 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SEGUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SEGUIDORES_PK" ON "HR"."PELIGROSOS" ("PELIGROSOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PELIGROSOS
--------------------------------------------------------

  ALTER TABLE "HR"."PELIGROSOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELIGROSOS" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELIGROSOS" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELIGROSOS" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELIGROSOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PELIGROSOS" ADD CONSTRAINT "SEGUIDORES_PK" PRIMARY KEY ("PELIGROSOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PELIGROSOS" MODIFY ("PELIGROSOS_ID" NOT NULL ENABLE);
