--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View JUGADORES_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LALIGA"."JUGADORES_VIEW" ("NOMBREJUGADOR", "NOMBREEQUIPO") AS 
  SELECT
j.NOMBRE,
e.NOMBRE
FROM
EQUIPOS e,
JUGADORES j
WHERE e.EQUIPO_ID = j.EQUIPO_ID
AND j.SALARIO > 2000
WITH READ ONLY;
--------------------------------------------------------
--  DDL for Table AFICION
--------------------------------------------------------

  CREATE TABLE "LALIGA"."AFICION" 
   (	"AFICION_ID" NUMBER, 
	"EQUIPO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CANTICOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."CANTICOS" 
   (	"CANTICOS_ID" NUMBER, 
	"AFICION_ID" NUMBER, 
	"CANCIONES" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."EQUIPOS" 
   (	"EQUIPO_ID" NUMBER, 
	"ESTADIO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "LALIGA"."EQUIPOS"."EQUIPO_ID" IS 'La Clave Primaria';
--------------------------------------------------------
--  DDL for Table ESTADIO
--------------------------------------------------------

  CREATE TABLE "LALIGA"."ESTADIO" 
   (	"ESTADIO_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "LALIGA"."JUGADORES" 
   (	"JUGADOR_ID" NUMBER, 
	"EQUIPO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDOS" VARCHAR2(30 BYTE), 
	"SALARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PELIGROSOS
--------------------------------------------------------

  CREATE TABLE "LALIGA"."PELIGROSOS" 
   (	"PELIGROSOS_ID" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDOS" VARCHAR2(40 BYTE), 
	"DNI" NUMBER, 
	"FECHA_NACIMIENTO" DATE, 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into LALIGA.AFICION
SET DEFINE OFF;
Insert into LALIGA.AFICION (AFICION_ID,EQUIPO_ID,NOMBRE) values ('1','1','SUR');
REM INSERTING into LALIGA.CANTICOS
SET DEFINE OFF;
Insert into LALIGA.CANTICOS (CANTICOS_ID,AFICION_ID,CANCIONES) values ('1','1','FONDO');
REM INSERTING into LALIGA.EQUIPOS
SET DEFINE OFF;
Insert into LALIGA.EQUIPOS (EQUIPO_ID,ESTADIO_ID,NOMBRE) values ('1','1','REAL MADRID');
REM INSERTING into LALIGA.ESTADIO
SET DEFINE OFF;
Insert into LALIGA.ESTADIO (ESTADIO_ID) values ('1');
REM INSERTING into LALIGA.JUGADORES
SET DEFINE OFF;
Insert into LALIGA.JUGADORES (JUGADOR_ID,EQUIPO_ID,NOMBRE,APELLIDOS,SALARIO) values ('1','1','DANI','CARVAJAL','2500');
REM INSERTING into LALIGA.PELIGROSOS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."EQUIPO_PK" ON "LALIGA"."EQUIPOS" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AFICION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."AFICION_PK" ON "LALIGA"."AFICION" ("AFICION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SEGUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."SEGUIDORES_PK" ON "LALIGA"."PELIGROSOS" ("PELIGROSOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CANTICOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."CANTICOS_PK" ON "LALIGA"."CANTICOS" ("CANTICOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."ESTADIO_PK" ON "LALIGA"."ESTADIO" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JUGADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LALIGA"."JUGADORES_PK" ON "LALIGA"."JUGADORES" ("JUGADOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "LALIGA"."JUGADORES" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."JUGADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."JUGADORES" MODIFY ("JUGADOR_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."JUGADORES" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."JUGADORES" ADD CONSTRAINT "JUGADORES_PK" PRIMARY KEY ("JUGADOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PELIGROSOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."PELIGROSOS" MODIFY ("PELIGROSOS_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."PELIGROSOS" ADD CONSTRAINT "SEGUIDORES_PK" PRIMARY KEY ("PELIGROSOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."PELIGROSOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."PELIGROSOS" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."PELIGROSOS" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."PELIGROSOS" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."PELIGROSOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."CANTICOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."CANTICOS" MODIFY ("CANTICOS_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."CANTICOS" ADD CONSTRAINT "CANTICOS_PK" PRIMARY KEY ("CANTICOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."CANTICOS" MODIFY ("CANCIONES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADIO
--------------------------------------------------------

  ALTER TABLE "LALIGA"."ESTADIO" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."ESTADIO" ADD CONSTRAINT "ESTADIO_PK" PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AFICION" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AFICION" ADD CONSTRAINT "AFICION_PK" PRIMARY KEY ("AFICION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."AFICION" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."AFICION" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."EQUIPOS" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."EQUIPOS" ADD CONSTRAINT "EQUIPO_PK" PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LALIGA"."EQUIPOS" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
  ALTER TABLE "LALIGA"."EQUIPOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "LALIGA"."AFICION" ADD CONSTRAINT "EQUIPO_FK1" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LALIGA"."EQUIPOS" ("EQUIPO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."CANTICOS" ADD CONSTRAINT "AFICION_FK" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "LALIGA"."AFICION" ("AFICION_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."EQUIPOS" ADD CONSTRAINT "ESTADIO_FK" FOREIGN KEY ("ESTADIO_ID")
	  REFERENCES "LALIGA"."ESTADIO" ("ESTADIO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "LALIGA"."JUGADORES" ADD CONSTRAINT "EQUIPO_FK" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LALIGA"."EQUIPOS" ("EQUIPO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PELIGROSOS
--------------------------------------------------------

  ALTER TABLE "LALIGA"."PELIGROSOS" ADD CONSTRAINT "AFICION_FK1" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "LALIGA"."AFICION" ("AFICION_ID") ON DELETE SET NULL ENABLE;
